name 'levacic-phantomjs'
version '0.0.2'
source 'https://github.com/levacic/puppet-phantomjs'
author '3fs'
license 'MIT License'
summary 'Simple puppet module that installs PhantomJS - headless WebKit scriptable with a Javascript API.'
description 'Simple puppet module that installs PhantomJS - headless WebKit scriptable with a Javascript API.'
project_page 'https://github.com/levacic/puppet-phantomjs'